### ISSUE TITLE
node-thrust fail to install on Windows Enterprise

### ISSUE THREAD

**Issue by gliurn** [breach/thrust#265]
Hi, i tried to install node-thrust yesterday on my own computer and everything was ok but today when i tried on my work's computer i got this error, can you help me, i don t understand? is it because him under windows enterprise?

C:\Users\EXi471\Documents\thrust_tutorial>npm install node-thrust
-
> node-thrust@0.7.6-rc.1 postinstall C:\Users\EXi471\node_modules\node-thrust
> node scripts/bootstrap.js

C:\Users\EXi471\node_modules\node-thrust\vendor\thrust\.version
Creating: C:\Users\EXi471\node_modules\node-thrust\vendor\thrust
Downloading: https://github.com/breach/thrust/releases/download/v0.7.6/thrust-v0
.7.6-win32-ia32.zip
..
[2015-02-17T07:20:53.105Z] *********************************************
[2015-02-17T07:20:53.105Z] ERROR: tunneling socket could not be established, cau
se=getaddrinfo ENOTFOUND 80
[2015-02-17T07:20:53.120Z] *********************************************
[2015-02-17T07:20:53.120Z] Error: tunneling socket could not be established, cau
se=getaddrinfo ENOTFOUND 80
[2015-02-17T07:20:53.120Z]     at ClientRequest.onError (C:\Users\EXi471\node_mo
dules\node-thrust\node_modules\request\node_modules\tunnel-agent\index.js:168:17
)
[2015-02-17T07:20:53.120Z]     at ClientRequest.g (events.js:199:16)
[2015-02-17T07:20:53.120Z]     at ClientRequest.emit (events.js:107:17)
[2015-02-17T07:20:53.120Z]     at Socket.socketErrorListener (_http_client.js:27
2:9)
[2015-02-17T07:20:53.120Z]     at Socket.emit (events.js:107:17)
[2015-02-17T07:20:53.120Z]     at net.js:923:16
[2015-02-17T07:20:53.120Z]     at process._tickCallback (node.js:355:11)
[2015-02-17T07:20:53.136Z] ---------------------------------------------
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-thrust"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-thrust@0.7.6-rc.1 postinstall: `node scripts/bootstrap.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-thrust@0.7.6-rc.1 postinstall script 'node scripts/bootstrap.js'.
npm ERR! This is most likely a problem with the node-thrust package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/bootstrap.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-thrust
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\EXi471\Documents\thrust_tutorial\npm-debug.log

**Comment by miketheprogrammer** [comment]
What mom version. Looks like an https error

**Comment by miketheprogrammer** [comment]
Sorry nvm I'll look at this when I get into work and give a better response

**Comment by ctipper** [comment]
I'm brand new to node, I'm not sure I want to pursue this, but I just ran `npm install node-thrust` on my Mac system (OS X 10.9.5, macports version of node) and received much the same trace. It's not a permissions problem, npm is installed in the home folder, and this is all I have because the darn thing cleans up a light second after failing. :-)

3314 verbose about to build /Users/ctipper/.node/lib/node_modules/npm/node_modules/node-thrust
3315 info build /Users/ctipper/.node/lib/node_modules/npm/node_modules/node-thrust
3316 verbose linkStuff [ false,
3316 verbose linkStuff   false,
3316 verbose linkStuff   false,
3316 verbose linkStuff   '/Users/ctipper/.node/lib/node_modules/npm/node_modules' ]
3317 info linkStuff node-thrust@0.7.6-rc.1
3318 verbose linkBins node-thrust@0.7.6-rc.1
3319 verbose linkMans node-thrust@0.7.6-rc.1
3320 verbose rebuildBundles node-thrust@0.7.6-rc.1
3321 verbose rebuildBundles [ 'fs-extra', 'minimist', 'optimist', 'request', 'unzip' ]
3322 info install node-thrust@0.7.6-rc.1
3323 info postinstall node-thrust@0.7.6-rc.1
3324 verbose unsafe-perm in lifecycle true
3325 info node-thrust@0.7.6-rc.1 Failed to exec postinstall script
3326 verbose unlock done using /Users/ctipper/.npm/_locks/node-thrust-3cf55217f4a98430.lock for /Users/ctipper/.node/lib/node_modules/npm/node_modules/node-thrust
3327 verbose stack Error: node-thrust@0.7.6-rc.1 postinstall: `node scripts/bootstrap.js`
3327 verbose stack Exit status 1
3327 verbose stack     at EventEmitter.<anonymous> (/Users/ctipper/.node/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
3327 verbose stack     at EventEmitter.emit (events.js:110:17)
3327 verbose stack     at ChildProcess.<anonymous> (/Users/ctipper/.node/lib/node_modules/npm/lib/utils/spawn.js:14:12)
3327 verbose stack     at ChildProcess.emit (events.js:110:17)
3327 verbose stack     at maybeClose (child_process.js:1008:16)
3327 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
3328 verbose pkgid node-thrust@0.7.6-rc.1
3329 verbose cwd /Users/ctipper/.node/lib/node_modules/npm
3330 error Darwin 13.4.0
3331 error argv "node" "/Users/ctipper/.node/bin/npm" "install" "node-thrust"
3332 error node v0.12.0
3333 error npm  v2.7.4
3334 error code ELIFECYCLE
3335 error node-thrust@0.7.6-rc.1 postinstall: `node scripts/bootstrap.js`
3335 error Exit status 1
3336 error Failed at the node-thrust@0.7.6-rc.1 postinstall script 'node scripts/bootstrap.js'.
3336 error This is most likely a problem with the node-thrust package,
3336 error not with npm itself.
3336 error Tell the author that this fails on your system:
3336 error     node scripts/bootstrap.js
3336 error You can get their info via:
3336 error     npm owner ls node-thrust
3336 error There is likely additional logging output above.
3337 verbose exit [ 1, true ]
3338 verbose unbuild node_modules/node-thrust
3339 info preuninstall node-thrust@0.7.6-rc.1
3340 info uninstall node-thrust@0.7.6-rc.1
3341 verbose unbuild rmStuff node-thrust@0.7.6-rc.1 from /Users/ctipper/.node/lib/node_modules/npm/node_modules
3342 info postuninstall node-thrust@0.7.6-rc.1
3343 silly gentlyRm /Users/ctipper/.node/lib/node_modules/npm/node_modules/node-thrust is being purged from base /Users/ctipper/.node/lib/node_modules/npm
3344 verbose gentlyRm don't care about contents; nuking /Users/ctipper/.node/lib/node_modules/npm/node_modules/node-thrust
3345 silly vacuum-fs purging /Users/ctipper/.node/lib/node_modules/npm/node_modules/node-thrust
3346 silly vacuum-fs quitting because other entries in /Users/ctipper/.node/lib/node_modules/npm/node_modules

**Comment by alanbsmith** [comment]
Was this resolved? It looks like I'm having the same error as @ctipper. It seems to be an issue with bootstrap.js. I'm getting error code 9.

I created a directory and ran `npm install node-thrust` as stated by the readme.

And this is the error being thrown:

```
[2015-05-16T16:17:05.237Z] *********************************************
[2015-05-16T16:17:05.238Z] ERROR: Extraction failed with code: 9
[2015-05-16T16:17:05.239Z] *********************************************
[2015-05-16T16:17:05.267Z] boostrap:failed_extraction: Extraction failed with code: 9
[2015-05-16T16:17:05.267Z]     at Object.exports.err (/Users/alanbsmith/personal_projects/javascript/browser/node_modules/node-thrust/lib/common.js:311:13)
[2015-05-16T16:17:05.267Z]     at ChildProcess.<anonymous> (/Users/alanbsmith/personal_projects/javascript/browser/node_modules/node-thrust/scripts/bootstrap.js:125:31)
[2015-05-16T16:17:05.267Z]     at ChildProcess.emit (events.js:110:17)
[2015-05-16T16:17:05.267Z]     at maybeClose (child_process.js:1015:16)
[2015-05-16T16:17:05.267Z]     at Socket.<anonymous> (child_process.js:1183:11)
[2015-05-16T16:17:05.267Z]     at Socket.emit (events.js:107:17)
[2015-05-16T16:17:05.267Z]     at Pipe.close (net.js:485:12)
[2015-05-16T16:17:05.267Z] ---------------------------------------------
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-thrust"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! node-thrust@0.7.6-rc.1 postinstall: `node scripts/bootstrap.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-thrust@0.7.6-rc.1 postinstall script 'node scripts/bootstrap.js'.
npm ERR! This is most likely a problem with the node-thrust package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/bootstrap.js
```

I'll poke around a bit more with it, but if you have any ideas, I'd love some input. Thanks!

**Comment by alanbsmith** [comment]
Oh okay. It appears, at least for me, that the post-install for thrust was failing (maybe a timeout?). But I tried a few more times, and it works now. Sorry about the noise! Excited about the project!
