### ISSUE TITLE
Cannot install on Ubuntu

### ISSUE THREAD

**Issue by josegomezr** [breach/thrust#275]
Hi there, i've followed the very simple example of installation explained in the demo:

```
npm install -g \
  https://gist.github.com/morganrallen/f07f59802884bcdcad4a/download
```

And I get this error:

```
$ sudo npm install -g https://gist.github.com/morganrallen/f07f59802884bcdcad4a/download
/
> node-thrust@0.7.6-rc.1 postinstall /usr/local/lib/node_modules/jankybrowser/node_modules/node-thrust
> node scripts/bootstrap.js

/usr/local/lib/node_modules/jankybrowser/node_modules/node-thrust/vendor/thrust/.version
Creating: /usr/local/lib/node_modules/jankybrowser/node_modules/node-thrust/vendor/thrust
Downloading: https://github.com/breach/thrust/releases/download/v0.7.6/thrust-v0.7.6-linux-ia32.zip
.
Extracting /usr/local/lib/node_modules/jankybrowser/node_modules/node-thrust/vendor/thrust/thrust-v0.7.6-linux-ia32.zip

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: invalid signature: 0x4f44213c
    at /usr/local/lib/node_modules/jankybrowser/node_modules/node-thrust/node_modules/unzip/lib/parse.js:59:13
    at processImmediate [as _immediateCallback] (timers.js:345:15)

npm ERR! node-thrust@0.7.6-rc.1 postinstall: `node scripts/bootstrap.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the node-thrust@0.7.6-rc.1 postinstall script.
npm ERR! This is most likely a problem with the node-thrust package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/bootstrap.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-thrust
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-49-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "https://gist.github.com/morganrallen/f07f59802884bcdcad4a/download"
npm ERR! cwd /home/asistente04/thrust-test
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

```

So far I haven't made it work!

**Comment by morganrallen** [comment]
This looks like it could be a download error, unzip isn't seeing the file
as a valid zip. Have you tried again recently?

On Fri, Apr 24, 2015 at 12:28 PM, Jose Gomez <notifications@github.com>
wrote:

> Hi there, i've followed the very simple example of installation explained
> in the demo:
>
> npm install -g \
>   https://gist.github.com/morganrallen/f07f59802884bcdcad4a/download
>
> And I get this error:
>
> $ sudo npm install -g https://gist.github.com/morganrallen/f07f59802884bcdcad4a/download
> /
> > node-thrust@0.7.6-rc.1 postinstall /usr/local/lib/node_modules/jankybrowser/node_modules/node-thrust
> > node scripts/bootstrap.js
>
> /usr/local/lib/node_modules/jankybrowser/node_modules/node-thrust/vendor/thrust/.version
> Creating: /usr/local/lib/node_modules/jankybrowser/node_modules/node-thrust/vendor/thrust
> Downloading: https://github.com/breach/thrust/releases/download/v0.7.6/thrust-v0.7.6-linux-ia32.zip
> .
> Extracting /usr/local/lib/node_modules/jankybrowser/node_modules/node-thrust/vendor/thrust/thrust-v0.7.6-linux-ia32.zip
>
> events.js:72
>         throw er; // Unhandled 'error' event
>               ^
> Error: invalid signature: 0x4f44213c
>     at /usr/local/lib/node_modules/jankybrowser/node_modules/node-thrust/node_modules/unzip/lib/parse.js:59:13
>     at processImmediate [as _immediateCallback] (timers.js:345:15)
>
> npm ERR! node-thrust@0.7.6-rc.1 postinstall: `node scripts/bootstrap.js`
> npm ERR! Exit status 8
> npm ERR!
> npm ERR! Failed at the node-thrust@0.7.6-rc.1 postinstall script.
> npm ERR! This is most likely a problem with the node-thrust package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node scripts/bootstrap.js
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls node-thrust
> npm ERR! There is likely additional logging output above.
> npm ERR! System Linux 3.13.0-49-generic
> npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "https://gist.github.com/morganrallen/f07f59802884bcdcad4a/download"
> npm ERR! cwd /home/asistente04/thrust-test
> npm ERR! node -v v0.10.32
> npm ERR! npm -v 1.4.28
> npm ERR! code ELIFECYCLE
> npm ERR! not ok code 0
>
>
> So far I haven't made it work!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/breach/thrust/issues/275>.
>



-- 
http://ithoughtyouweretherobot.com
Metal and Wire

http://nolonelyguineapigs.com/
Wandering and Rambling

http://morglog.org
Old and Neglected.

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js v.1.20121007
Comment: http://openpgpjs.org

xsBNBFG3btUBB/9+/WJNOSIuc/praKPaPOweqXV5s7PGRD+HAnNWF/19YAY3
AFtfeoelhhY4sMJoobTaJzcZojznZ1kl/7UuuYCnbJO3Z9kaSMVrVxEZMSLe
YmW8Hc4ZsTnl9f05DQFy8ABpAvMLmXJQXh63BbfzjFqNbSWQfLhrubSM2Elq
xmN6EsmRyAuEeYlSnal+Di2MlViohpCbbagE2D6AZTUECIamTib6+DuLG4XO
b4GGKHR9TXu2qS1VH6hqcvdEz2MDE5OqZzAnBgcF2dvcOdTk9gAOoR1T+qKj
IJtg2X0ETbxcPqEXQoXE8VrxN0MLT5JQKTg26+csU4P2w0rEWsUsJombABEB
AAHNJU1vcmdhbiBBbGxlbiA8bW9yZ2FucmFsbGVuQGdtYWlsLmNvbT7CwFwE
EAECABAFAlG3btwJEG9pFLKaVEfeAAD7hwf+K8LN/kfgi8GTRLiTcuM+hSbm
uAeiBY+VaJIQFLzoFlt8A0hBlLNPFNNmUDxdPrMErdHgZ7HtJW/6RANuBTti
5hr3EBguH1GQyK7BbUqJGvaEX4UNRej3uyX3ufXDsIB/3NsKaTyyu+SO0+Hv
Cn2DwmlfSXcPhoarx6Turizn/WwgtTN3tqrMWxxiCKWydLH5xYuz+23BLMdc
oF/zkbF+7ddFhmyfiFh4Ej9//tsfwPj2cACU3uLTrcwCo7IxUtkrqMF/fhlm
LEqjhzDDjq9v7GNWb/5xB2xgTaucJ7/ljuS8nPlZqwCI8NlTgSqC8nyVLyjS
yVtOzkItcS0UqyW1Mg==
=V/Ia
-----END PGP PUBLIC KEY BLOCK-----

**Comment by josegomezr** [comment]
@morganrallen I've just tried and got the same error.

I tried downloading it my self and got 404 error on [ia32]( https://github.com/breach/thrust/releases/download/v0.7.6/thrust-v0.7.6-linux-ia32.zip
) package
