### ISSUE TITLE
Unable to run bootstrap.py on windows XP Service Pack 3

### ISSUE THREAD

**Issue by kungfoochris** [breach/thrust#276]
I have python install, git installed, and the python exe is in the path.

This is the output I get when running bootstrap.py:

C:\Documents and Settings\User\Desktop\thrust\scripts>bootstrap.py
Traceback (most recent call last):
  File "vendor\brightray\vendor\gyp\gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "vendor\brightray\vendor\gyp\pylib\gyp\__init__.py", line 534, in script_main
    return main(sys.argv[1:])
  File "vendor\brightray\vendor\gyp\pylib\gyp\__init__.py", line 527, in main
    return gyp_main(args)
  File "vendor\brightray\vendor\gyp\pylib\gyp\__init__.py", line 512, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "vendor\brightray\vendor\gyp\pylib\gyp\generator\ninja.py", line 2206, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
TypeError: object of type 'NoneType' has no len()

Traceback (most recent call last):
  File "C:\Documents and Settings\IEUser\Desktop\thrust\scripts\bootstrap.py", line 75, in <module>
    sys.exit(main())
  File "C:\Documents and Settings\IEUser\Desktop\thrust\scripts\bootstrap.py", line 30, in main
    update_thrust_shell()
  File "C:\Documents and Settings\IEUser\Desktop\thrust\scripts\bootstrap.py", line 71, in update_thrust_shell
    execute([sys.executable, update])
  File "C:\Documents and Settings\IEUser\Desktop\thrust\scripts\bootstrap.py", line 20, in execute
    raise e
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\Documents and Settings\\IEUser\\Desktop\\thrust\\scripts\\update.p
y']' returned non-zero exit status 1

**Comment by kungfoochris** [comment]
I have tried to build this from the source on Windows 7. My goal was to build this so that the 32bit version runs on windows XP. The binary we get when we use the go-thrust package doesn't run on windows xp.

Any suggestions are welcomed. 

On windows 7 I am able to run boostrap.py, and update.py. When I run build.py it errors with this output:

C:\Users\csmith\Desktop\thrust\scripts>build.py
ninja: Entering directory `out\Release'
[2/84] ACTION thrust_shell_js: xxd web_view.js_b122fa8cfef9005dc6cab43b26d26d07
FAILED: C:\Python27\python.exe gyp-win-tool action-wrapper environment.x86 thrust_shell_js_target_xxd_web_view_js_b122fa8cfef9005dc6cab43b26d26d07..rsp ..\..\
'xxd' is not recognized as an internal or external command,
operable program or batch file.
[2/84] ACTION thrust_shell_js: xxd remote.js_b122fa8cfef9005dc6cab43b26d26d07
FAILED: C:\Python27\python.exe gyp-win-tool action-wrapper environment.x86 thrust_shell_js_target_xxd_remote_js_b122fa8cfef9005dc6cab43b26d26d07..rsp ..\..\
'xxd' is not recognized as an internal or external command,
operable program or batch file.
ninja: build stopped: subcommand failed.

**Comment by kungfoochris** [comment]
I am able to get it to build on Windows 7 now without a problem. But the 32bit release build will not run on XP. Is there any chance of getting this to work within Windows XP?

**Comment by mcdermed** [comment]
I think with the planned move to Electron (Atom) it won't be possible. They've already said no to XP support https://github.com/atom/electron/issues/1775

**Comment by kungfoochris** [comment]
Gotcha, thanks for the reply. We will look at other options.
